version: '3.8'

services:
  1aides:
    build:
      context: ..
      dockerfile: Dockerfile
    image: serverless-100026543835-docker.pkg.coding.net/1aides/1aides/1aides:latest
    ports:
      - "8999:8999"
    environment:
      - TEMPLATE_PATH=/app/frontend/templates/*
      - STATIC_PATH=/app/frontend/static
      - MONGO_USER=aides
      - MONGO_PASSWORD=dGhpcyBpcyBhaWRlcw==
      - MONGO_HOST=mongo:27017
    volumes:
      - D:\volumes\1aides\logs:/logs
    depends_on:
      - mongo
    restart: always

  mongo:
    image: hub.atomgit.com/amd64/mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aides
      - MONGO_INITDB_ROOT_PASSWORD=dGhpcyBpcyBhaWRlcw==
    volumes:
      - D:\volumes\mongo:/data/db
    restart: always
